#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2
# Configures facebook.com to resolve to 8.8.8.8
# local host resolves to 127.0.0.2 

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
